name: flutter_debug_panel_example
description: Example app demonstrating the Flutter Debug Panel package
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_debug_panel:
    path: ../

dev_dependencies:
  test: ^1.0.0
